package mohsin.code.fragments

object Constants {

    fun getSongList(): ArrayList<Songs> {
        val songList = arrayListOf(
            Songs("Let Me Love You", "Dua Lipa"),
            Songs("Humdum", "Vishal"),
            Songs("Shape of You", "Ed Sheeran"),
            Songs("Blinding Lights", "The Weeknd"),
            Songs("Dance Monkey", "Tones and I"),
            Songs("Rockstar", "Post Malone"),
            Songs("Sunflower", "Post Malone"),
            Songs("Someone You Loved", "Lewis Capaldi"),
            Songs("Señorita", "Shawn Mendes"),
            Songs("Bad Guy", "Billie Eilish"),
            Songs("Old Town Road", "Lil Nas X"),
            Songs("Circles", "Post Malone"),
            Songs("Memories", "Maroon 5"),
            Songs("Adore You", "Harry Styles"),
            Songs("Perfect", "Ed Sheeran"),
            Songs("Levitating", "Dua Lipa"),
            Songs("Peaches", "Justin Bieber"),
            Songs("Good 4 U", "Olivia Rodrigo"),
            Songs("Save Your Tears", "The Weeknd"),
            Songs("Stay", "The Kid LAROI"),
            Songs("drivers license", "Olivia Rodrigo"),
            Songs("Montero", "Lil Nas X"),
            Songs("Watermelon Sugar", "Harry Styles"),
            Songs("Deja Vu", "Olivia Rodrigo"),
            Songs("Blinding Lights", "The Weeknd"),
            Songs("Positions", "Ariana Grande"),
            Songs("Afterglow", "Ed Sheeran"),
            Songs("Dynamite", "BTS"),
            Songs("Butter", "BTS"),
            Songs("Heat Waves", "Glass Animals"),
            Songs("Mood", "24kGoldn"),
            Songs("Industry Baby", "Lil Nas X"),
            Songs("WAP", "Cardi B"),
            Songs("Savage Love", "Jason Derulo"),
            Songs("Stuck with U", "Ariana Grande"),
            Songs("Intentions", "Justin Bieber"),
            Songs("Say So", "Doja Cat"),
            Songs("Laugh Now Cry Later", "Drake"),
            Songs("Life Goes On", "BTS"),
            Songs("Yummy", "Justin Bieber"),
            Songs("Everything I Wanted", "Billie Eilish"),
            Songs("Don't Start Now", "Dua Lipa"),
            Songs("Break My Heart", "Dua Lipa"),
            Songs("Physical", "Dua Lipa"),
            Songs("Rain on Me", "Lady Gaga"),
            Songs("Toosie Slide", "Drake"),
            Songs("Holy", "Justin Bieber"),
            Songs("Go Crazy", "Chris Brown"),
            Songs("POPSTAR", "DJ Khaled"),
            Songs("Blueberry Faygo", "Lil Mosey"),
            Songs("For the Night", "Pop Smoke"),
            Songs("Lemonade", "Internet Money"),
            Songs("The Box", "Roddy Ricch"),
            Songs("What's Poppin", "Jack Harlow"),
            Songs("Mood Swings", "Pop Smoke"),
            Songs("Bop", "DaBaby"),
            Songs("Laugh Now Cry Later", "Drake"),
            Songs("Savage", "Megan Thee Stallion"),
            Songs("Rockstar", "DaBaby"),
            Songs("Goosebumps", "Travis Scott"),
            Songs("Sunflower", "Post Malone"),
            Songs("ROXANNE", "Arizona Zervas"),
            Songs("Be Kind", "Marshmello"),
            Songs("Stunnin'", "Curtis Waters"),
            Songs("Roses", "SAINt JHN"),
            Songs("Circles", "Post Malone"),
            Songs("Come & Go", "Juice WRLD"),
            Songs("Sicko Mode", "Travis Scott"),
            Songs("Memories", "Maroon 5"),
            Songs("Lonely", "Justin Bieber"),
            Songs("Heartless", "The Weeknd"),
            Songs("Adore You", "Harry Styles"),
            Songs("Falling", "Harry Styles"),
            Songs("Before You Go", "Lewis Capaldi"),
            Songs("Blinding Lights", "The Weeknd"),
            Songs("Savage Love", "Jawsh 685"),
            Songs("Therefore I Am", "Billie Eilish"),
            Songs("Holy", "Justin Bieber"),
            Songs("Stunnin'", "Curtis Waters"),
            Songs("Laugh Now Cry Later", "Drake"),
            Songs("Watermelon Sugar", "Harry Styles"),
            Songs("positions", "Ariana Grande"),
            Songs("Monster", "Shawn Mendes"),
            Songs("Levitating", "Dua Lipa"),
            Songs("Peaches", "Justin Bieber"),
            Songs("Good 4 U", "Olivia Rodrigo"),
            Songs("drivers license", "Olivia Rodrigo"),
            Songs("Deja Vu", "Olivia Rodrigo"),
            Songs("Montero", "Lil Nas X"),
            Songs("Stay", "The Kid LAROI"),
            Songs("Save Your Tears", "The Weeknd"),
            Songs("Blinding Lights", "The Weeknd"),
            Songs("Someone You Loved", "Lewis Capaldi"),
            Songs("Sunflower", "Post Malone"),
            Songs("Rockstar", "Post Malone"),
            Songs("Dance Monkey", "Tones and I"),
            Songs("Shape of You", "Ed Sheeran"),
            Songs("Humdum", "Vishal")
        )

        return songList
    }

}